

import React, { useState } from 'react';
import PageTitle from '../components/PageTitle';
import { THEME_COLORS } from '../constants';

interface FAQItemProps {
  question: string;
  answer: string | React.ReactNode;
}

const FAQItem: React.FC<FAQItemProps> = ({ question, answer }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className={`border-b border-${THEME_COLORS.border}`}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex justify-between items-center w-full py-5 px-1 text-left"
        aria-expanded={isOpen}
      >
        <span className={`text-lg font-medium text-${THEME_COLORS.textBase}`}>{question}</span>
        <svg
          className={`w-5 h-5 text-${THEME_COLORS.primary} transform transition-transform duration-200 ${isOpen ? 'rotate-180' : 'rotate-0'}`}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"></path>
        </svg>
      </button>
      {isOpen && (
        <div className={`pb-5 px-1 text-${THEME_COLORS.textMuted} leading-relaxed animate-fadeIn`}>
          {typeof answer === 'string' ? <p>{answer}</p> : answer}
        </div>
      )}
    </div>
  );
};


const FAQPage: React.FC = () => {
  const faqs: FAQItemProps[] = [
    {
      question: "What is fractional ownership?",
      answer: "Fractional ownership allows multiple investors to co-own a high-value asset, like a luxury villa. Each investor owns a share (or fraction) of the property, making it more affordable and accessible than sole ownership. You get to enjoy the benefits of ownership (like rental income and potential appreciation) proportional to your share."
    },
    {
      question: "How does Spacez select properties?",
      answer: "Our expert team conducts thorough due diligence, analyzing market trends, location advantages, property condition, and potential for rental income and capital appreciation. We only list properties that meet our stringent quality and investment criteria."
    },
    {
      question: "What are the minimum investment amounts?",
      answer: "Minimum investment amounts vary per property but are designed to be accessible. Typically, they start from ₹1,00,000. You can find the specific minimum investment for each property on its detail page."
    },
    {
      question: "How do I earn returns?",
      answer: (
          <>
            <p>Investors primarily earn returns in two ways:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li><strong>Rental Income:</strong> You receive a share of the net rental income generated by the property, distributed monthly or quarterly.</li>
                <li><strong>Capital Appreciation:</strong> If the property's value increases over time, your share value also increases. You can realize this gain upon selling your share (exit opportunities will be outlined per property).</li>
            </ul>
          </>
      )
    },
    {
      question: "Who manages the property and rentals?",
      answer: "Spacez, or its designated professional property management partners, handles all aspects of property management. This includes maintenance, guest bookings, hospitality services, and financial reporting, ensuring a hassle-free experience for investors."
    },
    {
        question: "Can I sell my share?",
        answer: "Yes, there will be mechanisms to sell your share. Spacez aims to facilitate a secondary market or defined exit windows for investors. The specific terms for liquidity will be detailed in the investment agreement for each property."
    }
  ];

  return (
    <div className="container mx-auto px-6 py-12 min-h-[calc(100vh-300px)]">
      <PageTitle title="Frequently Asked Questions" subtitle="Find answers to common questions about investing with Spacez." />
      
      <div className={`bg-${THEME_COLORS.cardBackground} p-6 md:p-10 rounded-lg shadow-xl`}>
        <div className="max-w-3xl mx-auto">
          {faqs.map((faq, index) => (
            <FAQItem key={index} question={faq.question} answer={faq.answer} />
          ))}
        </div>
        <div className="mt-10 text-center">
            <p className={`text-lg text-${THEME_COLORS.textMuted} mb-3`}>Can't find the answer you're looking for?</p>
            <a 
                href="/contact-support" 
                className={`inline-block bg-${THEME_COLORS.primary} text-white font-semibold py-3 px-6 rounded-lg text-md hover:bg-blue-700 transition-colors shadow-md`}
            >
                Contact Our Support Team
            </a>
        </div>
      </div>
    </div>
  );
};

export default FAQPage;